name: Build & Release Image
on:
    push:
      tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
        contents: read
    steps:
    - name: Get Code
      uses: actions/checkout@v4
    
    - name: Setup go environment
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    
    - name: Download dependencies
      run: go mod download
    - name: Run tests
      run: go test -v ./...
  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
        packages: write
    steps:
    - name: Get Code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Set environment variables
      run: |
        RELEASE_VERSION=${GITHUB_REF#refs/tags/}
        echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
        echo "IMG=ghcr.io/thg-ice/kuberhealthy-storage-check:${RELEASE_VERSION}" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ env.IMG }}
